{
 "title": "E-Commerce Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Overview" } },
  {
   "title": "Total Customers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT unique_customers FROM overview_index LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT unique_transactions as \"Total\", cancel_transactions as \"Canceled\" FROM overview_index LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT amount as \"Total\", avg_by_customer as \"Avg. per person\", avg_by_transaction as \"Avg. per transaction\" FROM overview_index LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Customers in 2011",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT mon, unique_customers FROM overview_by_months LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Successful Transactions in 2011",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT mon, unique_transactions FROM overview_by_months LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenue in 2011",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT mon, amount FROM overview_by_months LIMIT 50 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "## RFM Analysis\n- Recency(R): Days('2011-12-09') since last purchase\n- Frequency(F): Total number of purchases\n- Monetary(M): Total money this customer spent."
   }
  },
  {
   "title": "Average of Recency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(recency) FROM rfm LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average of Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(frequency) FROM rfm LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average of Monetary",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(monetary) FROM rfm LIMIT 50 "
    }
   ]
  },
  {
   "title": "Recency",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(customer_id), recency FROM rfm GROUP BY recency LIMIT 50 "
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT customer_id, frequency FROM rfm LIMIT 50 "
    }
   ]
  },
  {
   "title": "Monetary",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT customer_id, monetary FROM rfm LIMIT 50 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "## Customer segments with RFM Model\n- Champions: Bought recently, buy often and spend the most.\n- Loyal: Spend good money with us often. Responsive to promotions\n- Potential Loyalist: Recent customers, but spent a good amount and bought more than once.\n- New Customers: Bought most recently, but not often.\n- Promising: Recent shoppers, but haven't spent much.\n- Need Attention: Above average recency frequency and monetary values. May not have bought very recently though.\n- About To Sleep: Below average recency frequency and monetary values. Will lose them if not reactivated.\n- At Risk: Spent big money and purchased often. But long time ago. Need to bring them back!\n- Cannot Lose Them: Made biggest purchases, and often. But haven't returned for a long time.\n- Hibernating Customers: Last purchase was long back, low spenders and low number of orders.\n- Lost Customers: Lowest recency, frequency and monetary scores.\n"
   }
  },
  {
   "title": "Percentage of Customers by Segments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT customer_segment, segment_percentage FROM rfm_segment_percentage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Top50 Big Spenders",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT customer_id, customer_segment, monetary,recency, frequency FROM rfm \r\nwhere customer_id!='NaN'\r\nORDER BY monetary DESC  LIMIT 50"
    }
   ]
  }
 ]
}